# Generated by Django 4.0.3 on 2023-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='employment/media/employment/default.png', upload_to=''),
        ),
    ]
