# Generated by Django 4.0.3 on 2023-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_CV',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
