# Generated by Django 4.0.3 on 2023-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_user_profile_pic_alter_user_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='employment/default.png', upload_to='employment/'),
        ),
    ]
