# Generated by Django 4.0.3 on 2023-12-30 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_remove_user_requests_user_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='requests',
            new_name='CV_requests',
        ),
        migrations.AddField(
            model_name='user',
            name='job_requests',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
