# Generated by Django 4.0.3 on 2023-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_user_has_cv_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='job',
            field=models.CharField(default='engineer', max_length=64),
        ),
        migrations.AddField(
            model_name='cv',
            name='major',
            field=models.CharField(default='chemical engineering', max_length=64),
        ),
    ]
