# Generated by Django 4.0.3 on 2023-12-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_cv_job_cv_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('salary', models.CharField(default='0', max_length=64)),
                ('job', models.CharField(default='engineer', max_length=64)),
                ('major', models.CharField(default='chemical engineering', max_length=64)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
