# Generated by Django 4.0.3 on 2023-12-30 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_rename_requests_user_cv_requests_user_job_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
