# Generated by Django 4.0.3 on 2023-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes_num',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
