# Generated by Django 4.0.3 on 2023-12-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_posts_likes_num_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('following', 'followers')},
        ),
    ]
