# Generated by Django 4.0.3 on 2023-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlistings_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='creator',
            field=models.CharField(default='walid', max_length=64),
            preserve_default=False,
        ),
    ]
