# Generated by Django 4.0.3 on 2023-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlistings_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
