# Generated by Django 4.0.3 on 2023-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
