# Generated by Django 4.0.3 on 2023-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_highest_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(default='Electronics', max_length=64),
            preserve_default=False,
        ),
    ]
