# Generated by Django 4.0.3 on 2023-09-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlistings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='commentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
