# Generated by Django 4.0.3 on 2023-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlistings_comment_comments_commentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='comment',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.comments'),
        ),
    ]
