# Generated by Django 4.0.3 on 2023-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auctionlistings_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
